title: Literary Vault API
description: API for retrieving quiz questions across various subjects
baseurl: "/LITERARY-API-HOST"
url: "https://exios66.github.io"
markdown: kramdown
theme: jekyll-theme-minimal

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# API Settings
api_version: "v1"
enable_cors: true

# Collections
collections:
  questions:
    output: true

# Custom headers for API
include:
  - _headers

# Configure paths
defaults:
  - scope:
      path: "docs/data/csv"
    values:
      raw: true
  - scope:
      path: "docs/api/v1"
    values:
      layout: "null"