openapi: 3.1.0
info:
  title: Literary Vault API
  description: API for retrieving questions from the Literary Vault Database.
  version: 1.0.0
servers:
  - url: https://exios66.github.io/LITERARY-API-HOST
    description: GitHub Pages Server
paths:
  /api/v1/questions:
    get:
      operationId: getQuestions
      summary: Retrieve questions
      description: Fetches a list of questions with optional parameters
      parameters:
        - name: category
          in: query
          required: true
          description: The category of questions to retrieve
          schema:
            type: string
            enum:
              - astronomy
              - literature
              - mathematics
              - general-knowledge
              - psychology
              - american-history
        - name: limit
          in: query
          required: false
          description: The number of questions to retrieve
          schema:
            type: integer
            minimum: 1
            maximum: 50
            default: 10
        - name: difficulty
          in: query
          required: false
          description: Difficulty level of questions (0-3)
          schema:
            type: integer
            minimum: 0
            maximum: 3
        - name: random
          in: query
          required: false
          description: Whether to return random questions
          schema:
            type: boolean
            default: true
      responses:
        "200":
          description: A list of questions
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [success, error]
                  data:
                    type: object
                    properties:
                      questions:
                        type: array
                        items:
                          $ref: "#/components/schemas/Question"
components:
  schemas:
    Question:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the question
        question:
          type: string
          description: The question text
        correct_answer:
          type: string
          description: The correct answer
        incorrect_answers:
          type: array
          description: Array of incorrect answers
          items:
            type: string
          minItems: 3
          maxItems: 3
        difficulty:
          type: integer
          description: Difficulty level (0-3)
        category:
          type: string
          description: Question category
        topic_focus:
          type: string
          description: Specific topic within the category 