openapi: 3.1.0
info:
  title: Literary API Host - Quiz Questions
  description: API for retrieving quiz questions in various subjects, including Astronomy, Literature, Mathematics, General Knowledge, Psychology, and American History. Each category returns a CSV file with the questions.
  version: 1.0.0
servers:
  - url: https://exios66.github.io/LITERARY-API-HOST/docs/data
    description: Main server hosting quiz question data files
paths:
  /Astronomy-questions.csv:
    get:
      operationId: getAstronomyQuestions
      summary: Retrieve Astronomy quiz questions
      description: Returns a CSV file containing quiz questions on Astronomy.
      responses:
        '200':
          description: CSV file with Astronomy questions
          content:
            text/csv:
              schema:
                type: string
                format: binary
  /Literature-questions.csv:
    get:
      operationId: getLiteratureQuestions
      summary: Retrieve Literature quiz questions
      description: Returns a CSV file containing quiz questions on Literature.
      responses:
        '200':
          description: CSV file with Literature questions
          content:
            text/csv:
              schema:
                type: string
                format: binary
  /Mathematics-questions.csv:
    get:
      operationId: getMathematicsQuestions
      summary: Retrieve Mathematics quiz questions
      description: Returns a CSV file containing quiz questions on Mathematics.
      responses:
        '200':
          description: CSV file with Mathematics questions
          content:
            text/csv:
              schema:
                type: string
                format: binary
  /General-Knowledge-questions.csv:
    get:
      operationId: getGeneralKnowledgeQuestions
      summary: Retrieve General Knowledge quiz questions
      description: Returns a CSV file containing quiz questions on General Knowledge.
      responses:
        '200':
          description: CSV file with General Knowledge questions
          content:
            text/csv:
              schema:
                type: string
                format: binary
  /Psychology-questions.csv:
    get:
      operationId: getPsychologyQuestions
      summary: Retrieve Psychology quiz questions
      description: Returns a CSV file containing quiz questions on Psychology.
      responses:
        '200':
          description: CSV file with Psychology questions
          content:
            text/csv:
              schema:
                type: string
                format: binary
  /American-History-questions.csv:
    get:
      operationId: getAmericanHistoryQuestions
      summary: Retrieve American History quiz questions
      description: Returns a CSV file containing quiz questions on American History.
      responses:
        '200':
          description: CSV file with American History questions
          content:
            text/csv:
              schema:
                type: string
                format: binary